### ISSUE TITLE
我的这个直接就崩溃了

### ISSUE THREAD

**Issue by MasterBetter** [zhnnnnn/ZHNformView#1]
我从网络请求的数据
就是按照你的那个格式，但是就崩了，蹦到这里了- (CGSize)p_boundingRectWithText:(NSString *)text size:(CGSize)size font:(CGFloat)font{
    NSDictionary *attribute = @{NSFontAttributeName: [UIFont systemFontOfSize:font]};
    CGSize retSize = [text boundingRectWithSize:size options:NSStringDrawingUsesLineFragmentOrigin attributes:attribute context:nil].size;
    return retSize;
}

**Comment by zhnnnnn** [comment]
奔溃打印给我看看，多给我点信息我好排查

**Comment by MasterBetter** [comment]
我已经解决了！就是context要在转一下nsstring

**Comment by zhnnnnn** [comment]
那就是你传的值不是string。。对吧

**Comment by MasterBetter** [comment]
我传的是后台返回来的数据，我在你封装的那个里面直接转啦
